### ISSUE TITLE
Display only 13 characters instead of 14 on 1 line

### ISSUE THREAD

**Issue by pierre83** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#36]
With a PCD8544 ( 84 x 48) compliant device.
For example : display.print(F("12345678901234"));
Display : 1234567890123
Display : 4

**Comment by bbx10** [comment]
This issue is caused by using Adafruit GFX library version1.1.x. Solution 1: Downgrade to version 1.0.2. Solution 2: Turn off text wrap then change print to println where needed. display.setTextWrap(false);
display.printfln("12345678901234");

I ended up using solution 2.

**Comment by pierre83** [comment]
Thanks !

Good weekend !
  ----- Original Message -----
