### ISSUE TITLE
SPI transaction switching required

### ISSUE THREAD

**Issue by bmuessig** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#39]
Arduino board:  Teensy 3.2

Using this library together with the SD library on the Teensy 3.2 does not work, as the SPI configurations are incompatible.

The Problem has been solved by changing the SPI send functions to:
```
void Adafruit_PCD8544::command(uint8_t c) {
  SPI.beginTransaction(SPI_SPEED);

  digitalWrite(_dc, LOW);
  if (_cs > 0)
    digitalWrite(_cs, LOW);
  spiWrite(c);
  if (_cs > 0)
    digitalWrite(_cs, HIGH);

  SPI.endTransaction();
}

void Adafruit_PCD8544::data(uint8_t c) {
  SPI.beginTransaction(SPI_SPEED);

  digitalWrite(_dc, HIGH);
  if (_cs > 0)
    digitalWrite(_cs, LOW);
  spiWrite(c);
  if (_cs > 0)
    digitalWrite(_cs, HIGH);

  SPI.endTransaction();
}
```

The start of the begin() function has been altered to:
```
if (!isHardwareSPI()) {
    // Setup hardware SPI.
    SPI.begin();
  }
  else {
    // Setup software SPI.
```

And the following line has been added to the Header file:
`#define SPI_SPEED  SPISettings(7500000, MSBFIRST, SPI_MODE0)`

**Comment by ladyada** [comment]
this should be fixed now with the move to busio!
