### ISSUE TITLE
Where to get font sign size in pixels to locate the sign in the middle of the screen?

### ISSUE THREAD

**Issue by bogus105** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#42]
Hi,

I have the following problem: i need to put random letter on the nokia 5110 display. the letter should be located in the middle of the display area. Letter font can vary as well as its size. As pixels x pixels size of each sign vary it is very difficult to calculate X,Y starting point of cursor to achieve the goal - sign displayed in the middle of the screen irrespecitive of its size, font and screen orientation...

Please point me how to get a sign size info from library.

**Comment by andrumar10** [comment]
Calculation of size will be performed in the core Adafruit graphics library https://github.com/adafruit/Adafruit-GFX-Library/
Adafruit_GFX.cpp will contain code describing how the core library handles the classic font (line 814) and custom fonts (line 828). Hopefully you can work backwards from this information to calculate the correct starting cursor position. 
Good luck! 😄
