### ISSUE TITLE
Is there a list of the display classes for this library?

### ISSUE THREAD

**Issue by Kintara** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#43]
I am a Noob to the Ardrino world and fining the PCD8544 library useful, but I dont understand some of the classes.
 I can see the example using things like
display.display()
display.setCursor(0,0)
display.print(NewValue)
display.println("Hello World")
But what else is there?
How do I find out?
How do I find out the syntax and use of the classes?

many thanks
Kintara 8-)

**Comment by mcauser** [comment]
Best place to look is the code. The [Adafruit_PCD8544.h](https://github.com/adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library/blob/master/Adafruit_PCD8544.h) file shows each of these methods and what arguments they support. Scroll down to `class Adafruit_PCD8544` and have a look at the `public:` methods. The first 3 are the constructors and these show how you can setup the display. The next few methods are what you can call to interact with the display. The class extends the [Adafruit_GFX](https://github.com/adafruit/Adafruit-GFX-Library) library. There's a bunch more methods in there for drawing graphics to the displays buffer. Check out the [Adafruit_GFX.h](https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_GFX.h) file for more methods.
