### ISSUE TITLE
Lattepanda with leonardo arduino.

### ISSUE THREAD

**Issue by iles05** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#45]
How to use this for lattepanda

**Comment by iles05** [comment]
How to set pin.

**Comment by drak7** [comment]
Check the Lattepanda docs for pinouts: http://docs.lattepanda.com/content/1st_edition/hardware_introduction/
Otherwise it should work just like a Leonardo. Check out this page as well: https://core-electronics.com.au/tutorials/arduino-with-lattepanda.html
