### ISSUE TITLE
Pin 11 and 13 Changes?

### ISSUE THREAD

**Issue by AlbertusTeseling** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#46]
Hi all.
I would like to know how to change the Pin 11 and Pin 13 inputs for the Nokia 5110 Adafruit PCD8544 sketch published.
Nowhere in the sketch is there reference to Pin11 and Pin 13. Only to the other pins.
Thanks

**Comment by drak7** [comment]
Pins 11 and 13 in the example are for hardware SPI and can't be changed, they're defined depending on the board you're using. Check out the [SPI reference](https://www.arduino.cc/en/Reference/SPI). In this case the constructor only takes 3 arguments: DC, CS, and RST.

If you want to use software SPI then you can define the SCLK and DIN pins (7 and 6 in the example). The constructor for this takes 5 arguments: SCLK, DIN, DC, CS, RST.
