### ISSUE TITLE
Is this library is not maintained anymore?

### ISSUE THREAD

**Issue by tobiasschuerg** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#48]
Would be nice if the PRs would be merged.

**Comment by mcauser** [comment]
There's unmerged pull requests from 2014, so I'd say they are focusing on other products.
They are [still selling them](https://www.adafruit.com/product/338) for $10 each. Not sure what the deal is.

The [python version](https://github.com/adafruit/Adafruit_Nokia_LCD) is much more up to date.

**Comment by ladyada** [comment]
i wasn't subscribed to this so didn't see the issues/prs. we'll take a look at this library in the next few weeks
