### ISSUE TITLE
Compile error:

### ISSUE THREAD

**Issue by Bavly9** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#61]
# A compile time error is showing up to me 

## In Nokia_LCD.cpp line 323: In member function 'bool Nokia_LCD::print(long unsigned int)'
variable-sized object 'number_as_string' may not be initialized 

    char number_as_string[length_as_string] = {0}; 

## This solution has worked for me 💯 
    char number_as_string[length_as_string];
    memset(  number_as_string, 0, length_as_string*sizeof(char) );

**Comment by caternuson** [comment]
That file is not part of this library. Are you getting that message trying to use the `pcdtest` example from this library?
