### ISSUE TITLE
Rotated screen only displays 6 rows, not 12?

### ISSUE THREAD

**Issue by paulrose71** [adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library#62]
Hi there, 
When I rotate the screen (to portrait) the screen still only displays 6 rows. Not 12? So the bottom half of the screen is blank, when I thought it would contain the balance of my text? Is this normal? I've searched the forum, and the internet for an answer, but can't find one? Thanks alot.
Paul

**Comment by kai-morich** [comment]
issue is solved

**Comment by ladyada** [comment]
thanks 🙂
